pipeline {
    agent any
    tools {
        // Install the Maven version configured as "maven3" and add it to the path.
        maven "maven3"
    }
    parameters {
        string(name: 'MAJOR_VERSION', defaultValue: '1', description: 'DefaultBranch')
        string(name: 'MINOR_VERSION', defaultValue: '0', description: 'DefaultBranch')
        booleanParam(name: 'isTest', defaultValue: true, description: 'enable or disable test')
        choice(name: 'ENV', choices: ['DEV', 'TEST', 'PROD'], description: 'Pick ENV. 1st array is default in choice array')
    }

    stages {
        stage('Build') {
            steps {
                sh """
                mvn versions:set versions:commit -DnewVersion="${MAJOR_VERSION}.${MINOR_VERSION}.${BUILD_NUMBER}"
                mvn -B -DskipTests clean package
                """
            }
        }
        stage('Test') {
            when {
                expression {
                    params.isTest
                }
            }
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            when {
                expression {
                    params.ENV == "PROD"
                }
            }
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
